[package]
name = "mijit"
version = "0.1.0"
authors = ["apt1002"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "mijit"
crate_type = ["rlib", "cdylib"]

[dependencies]
memmap = "0.6.2"
memoffset = "0.6"
indexmap = "1.4.0"

[dev-dependencies]
rand = "0.7"
bad64 = "0.2.0"

[dev-dependencies.iced-x86]
version = "1.2.0"
default-features = false
# See below for all features
features = ["std", "decoder", "nasm"]

[patch.crates-io]
bad64 = {git='https://github.com/apt1002/bad64', branch='main'}
